sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /cam3d/depth_registered/points_filtered
    max_range: 2.0
    point_subsample: 1
    shape_padding: 0.1
    shape_scale: 1.0

